### ISSUE TITLE
exception: the match filter must be an expression in an object

### ISSUE THREAD

**Issue by joshuataylor** [perftools/xhgui#111]
When clicking on an error that has been logged, the following occurs:
```
Aw shoot, Xhgui hit an error
127.0.0.1:27017: exception: the match filter must be an expression in an object

You should check the following things:

Ensure that Mongo has been started
That config/config.php has the right connection information.
That the cache/ directory has the correct permissions.
Stack trace

#0 xhgui/src/Xhgui/Profiles.php(172): MongoCollection->aggregate(Array)
#1 xhgui/src/Xhgui/Controller/Run.php(129): Xhgui_Profiles->getPercentileForUrl(90, NULL, Array)
#2 xhgui/src/routes.php(35): Xhgui_Controller_Run->url()
#3 [internal function]: {closure}()
#4 xhgui/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#5 xhgui/vendor/slim/slim/Slim/Slim.php(1302): Slim\Route->dispatch()
#6 xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(117): Slim\Middleware\MethodOverride->call()
#9 xhgui/src/Xhgui/Middleware/Render.php(11): Slim\Middleware\SessionCookie->call()
#10 xhgui/vendor/slim/slim/Slim/Slim.php(1251): Xhgui_Middleware_Render->call()
#11 xhgui/webroot/index.php(10): Slim\Slim->run()
#12 {main}
```

Mongo is started, cache has 777 recursive, config.php is a direct copy of the example.

Debug mode turned on:
```
Slim Application Error
The application could not run because of the following error:

Details

Type: Exception
Message: No profile data found.
File: xhgui/src/Xhgui/Profiles.php
Line: 288
Trace

#0 xhgui/src/Xhgui/Profiles.php(46): Xhgui_Profiles->_wrap(NULL)
#1 xhgui/src/Xhgui/Controller/Run.php(67): Xhgui_Profiles->get(NULL)
#2 xhgui/src/routes.php(30): Xhgui_Controller_Run->view()
#3 [internal function]: {closure}()
#4 xhgui/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#5 xhgui/vendor/slim/slim/Slim/Slim.php(1302): Slim\Route->dispatch()
#6 xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(117): Slim\Middleware\MethodOverride->call()
#9 xhgui/src/Xhgui/Middleware/Render.php(11): Slim\Middleware\SessionCookie->call()
#10 xhgui/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Xhgui_Middleware_Render->call()
#11 xhgui/vendor/slim/slim/Slim/Slim.php(1251): Slim\Middleware\PrettyExceptions->call()
#12 xhgui/webroot/index.php(10): Slim\Slim->run()
#13 {main}
```

**Comment by joshuataylor** [comment]
I ran into this again, on a "new" machine. Turns out my nginx config was being funky with xhgui, and using the example xhgui config worked perfectly.

**Comment by markstory** [comment]
Thanks for the update @joshuataylor

**Comment by yuzhewo** [comment]
me too! how to fix it?

**Comment by joshuataylor** [comment]
@yuzhewo are you running nginx? It's 99.95% your nginx config :)

**Comment by yuzhewo** [comment]
yes!!! i'am running nginx. i check my mogodb, no data was stored, Is the reason? now I first check the nginx configuration

**Comment by yuzhewo** [comment]
@joshuataylor Thank you so much for your help, it really is this reason! 
the right config is:
```
try_files $uri $uri/ /index.php?$uri&$args; 
```
i lost $uri&$args;  (⊙o⊙)…
