### ISSUE TITLE
PHP Fatal Error when url contains []

### ISSUE THREAD

**Issue by jwhitcraft** [perftools/xhgui#137]
I have a url that contains [] as parameter, and when I try and view that url's data it give me this error

```
[13-Apr-2015 16:46:24 America/New_York] PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Array to string conversion' in /Users/jwhitcraft/Sites/xhgui/vendor/twig/twig/lib/Twig/Extension/Core.php:694
Stack trace:
#0 [internal function]: Slim\Slim::handleErrors(8, 'Array to string...', '/Users/jwhitcra...', 694, Array)
#1 /Users/jwhitcraft/Sites/xhgui/vendor/twig/twig/lib/Twig/Extension/Core.php(694): implode(' ', Array)
#2 /Users/jwhitcraft/Sites/xhgui/cache/ec/2e/38c49ce3130f2f56b9e772e6eaad.php(62): twig_join_filter(Array, ' ')
#3 /Users/jwhitcraft/Sites/xhgui/cache/4b/6c/3433af02eb3730fe87c376661fbe.php(94): __TwigTemplate_ec2e38c49ce3130f2f56b9e772e6eaad->getproperty_list('GET', Array)
#4 [internal function]: __TwigTemplate_4b6c3433af02eb3730fe87c376661fbe->block_content(Array, Array)
#5 /Users/jwhitcraft/Sites/xhgui/vendor/twig/twig/lib/Twig/Template.php(133): call_user_func(Array, Array, Array)
#6 /Users/jwhitcraft/Sites/xhgui/cache/61/b5/69dd6e5cee09db188030c8370d73.php(109): Twig_Template->displayBlock('content', Array, Array)
#7 /Users/jwh in /Users/jwhitcraft/Sites/xhgui/vendor/twig/twig/lib/Twig/Template.php on line 279
```

The url looks like this in the db:
`/ent/rest/v10/Filters?max_num=20&filter%5B0%5D%5Bcreated_by%5D=1&filter%5B1%5D%5Bmodule_name%5D=Accounts`
and this in the web request
`/ent/rest/v10/Filters?max_num=20&filter[0][created_by]=1&filter[1][module_name]=Accounts`

**Comment by markstory** [comment]
I checked this today, and it seems to be fixed. Complex query parameters are now serialized to JSON in the view page.
