### ISSUE TITLE
Custom View default values generates an error

### ISSUE THREAD

**Issue by ImpressiveDev** [perftools/xhgui#188]
The "Values to retrieve" input with default values:

```
{"meta" : true, "profile.main()" : true}
```

Generates:

```
#0 /var/www/xhgui/vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoCollection.php(461): Slim\Slim::handleErrors(4096, &#039;Argument 1 pass...&#039;, &#039;/var/www/xhgui/...&#039;, 461, Array)
#1 /var/www/xhgui/src/Xhgui/Profiles.php(33): MongoCollection-&gt;find(Object(stdClass), Object(stdClass))
#2 /var/www/xhgui/src/Xhgui/Controller/Custom.php(57): Xhgui_Profiles-&gt;query(Object(stdClass), Object(stdClass))
#3 /var/www/xhgui/src/routes.php(98): Xhgui_Controller_Custom-&gt;query()
#4 [internal function]: {closure}()
#5 /var/www/xhgui/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#6 /var/www/xhgui/vendor/slim/slim/Slim/Slim.php(1302): Slim\Route-&gt;dispatch()
#7 /var/www/xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim-&gt;call()
#8 /var/www/xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash-&gt;call()
#9 /var/www/xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(117): Slim\Middleware\MethodOverride-&gt;call()
#10 /var/www/xhgui/src/Xhgui/Middleware/Render.php(11): Slim\Middleware\SessionCookie-&gt;call()
#11 /var/www/xhgui/vendor/slim/slim/Slim/Slim.php(1251): Xhgui_Middleware_Render-&gt;call()
#12 /var/www/xhgui/webroot/index.php(10): Slim\Slim-&gt;run()
#13 {main}
```

Running on NGinx 1.10, PHP 7.0.8 and MongoDB 3.0.7.

**Comment by thias** [comment]
I have the same error, and here's the full PHP message I'm seeing with the current master code :

**Comment by laynefyc** [comment]
$res = $this->_profiles->query($query, $retrieve)->limit($perPage);

$query and $retrieve  is not array in this code.

$query = json_decode($request->post('query'),true);
$retrieve = json_decode($request->post('retrieve'),true);

The function json_decode()  have to set second parameters as 'true'.

**Comment by markstory** [comment]
@laynefyc Any chance you could open a pull request to fix that problem?

**Comment by lauripiisang** [comment]
Seems like the pull request that's been merged addresses this issue, so closing this
