### ISSUE TITLE
The 'cursor' option is required, except for aggregate with the explain argument

### ISSUE THREAD

**Issue by hegoku** [perftools/xhgui#232]
Env:
macos 10.12.6
php7.1
mongodb 3.6.2

When I view `http://127.0.0.1/xhgui-branch/webroot/url/view?url=%2Fsys3%2Fcompany-service%2Fweb%2FgetSubmitStatus` ,  this error occurs:

```
Aw shoot, Xhgui hit an error
The 'cursor' option is required, except for aggregate with the explain argument

You should check the following things:

Ensure that Mongo has been started
That config/config.php has the right connection information.
That the cache/ directory has the correct permissions.
Stack trace
#0 /web/xhgui-branch/vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoCollection.php(173): Alcaeus\MongoDbAdapter\ExceptionConverter::toLegacy(Object(MongoDB\Driver\Exception\RuntimeException), 'MongoResultExce...')
#1 /web/xhgui-branch/src/Xhgui/Profiles.php(138): MongoCollection->aggregate(Array)
#2 /web/xhgui-branch/src/Xhgui/Controller/Run.php(148): Xhgui_Profiles->getPercentileForUrl(90, '/sys3/company-s...', Array)
#3 /web/xhgui-branch/src/routes.php(35): Xhgui_Controller_Run->url()
#4 [internal function]: {closure}()
#5 /web/xhgui-branch/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#6 /web/xhgui-branch/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#7 /web/xhgui-branch/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#8 /web/xhgui-branch/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#9 /web/xhgui-branch/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()
#10 /web/xhgui-branch/src/Xhgui/Middleware/Render.php(11): Slim\Middleware\SessionCookie->call()
#11 /web/xhgui-branch/vendor/slim/slim/Slim/Slim.php(1300): Xhgui_Middleware_Render->call()
#12 /web/xhgui-branch/webroot/index.php(10): Slim\Slim->run()
#13 {main}
```

**Comment by hegoku** [comment]
Update to last version resolved

**Comment by Zaporozhec7** [comment]
I have same problem, but with latest Xhgui (0.9.0). 
MongoDB: 3.6.0
PHP: 7.1.15
Xhgui: 0.9.0

@hegoku , in "Update to last version resolved" you mean last bersion of Xhgui?
