### ISSUE TITLE
PDO: If empty database there is a stacktrace

### ISSUE THREAD

**Issue by Mte90** [perftools/xhgui#349]
I am getting `General error: 1 no such table: results` with an empty sqlite file.
```
#0 /srv/www/default/xhgui/src/Xhgui/Db/PdoRepository.php(90): PDO->prepare('\n          SELE...')
#1 /srv/www/default/xhgui/src/Xhgui/Searcher/PdoSearcher.php(108): XHGui\Db\PdoRepository->countByUrl('')
#2 /srv/www/default/xhgui/src/Xhgui/Controller/RunController.php(48): XHGui\Searcher\PdoSearcher->getAll(Array)
#3 /srv/www/default/xhgui/src/routes.php(45): XHGui\Controller\RunController->index(Object(Slim\Http\Request), Object(Slim\Http\Response))
#4 [internal function]: {closure}()
#5 /srv/www/default/xhgui/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#6 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#7 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#8 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#9 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()
#10 /srv/www/default/xhgui/src/Xhgui/Middleware/RenderMiddleware.php(14): Slim\Middleware\SessionCookie->call()
#11 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1300): XHGui\Middleware\RenderMiddleware->call()
#12 /srv/www/default/xhgui/webroot/index.php(13): Slim\Slim->run()
#13 {main}
```
If I run xhgui in a page with tideways the error changes and the file now has some content.

I get another error `Undefined variable: direction`:

```
#0 /srv/www/default/xhgui/src/Xhgui/Searcher/PdoSearcher.php(116): Slim\Slim::handleErrors(8, 'Undefined varia...', '/srv/www/defaul...', 116, Array)
#1 /srv/www/default/xhgui/src/Xhgui/Controller/RunController.php(48): XHGui\Searcher\PdoSearcher->getAll(Array)
#2 /srv/www/default/xhgui/src/routes.php(45): XHGui\Controller\RunController->index(Object(Slim\Http\Request), Object(Slim\Http\Response))
#3 [internal function]: {closure}()
#4 /srv/www/default/xhgui/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#5 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#6 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()
#9 /srv/www/default/xhgui/src/Xhgui/Middleware/RenderMiddleware.php(14): Slim\Middleware\SessionCookie->call()
#10 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1300): XHGui\Middleware\RenderMiddleware->call()
#11 /srv/www/default/xhgui/webroot/index.php(13): Slim\Slim->run()
#12 {main}
``` 

Looking at https://github.com/perftools/xhgui/blob/9d02c131b77604f409e98f9472589886dd3b6c34/src/Xhgui/Searcher/PdoSearcher.php#L116 that variable indeed is not defined at all in that function.

So I guess that they are 2 different issues, an empty db that is not filled with tables and a bad refactoring (maybe?).

Ref: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2261

**Comment by glensc** [comment]
one issue per one problem, please.

does your problem go away if you record one profiling? previously all SQL errors were ignored, so as a result the error is now thrown that was previously ignored.

**Comment by Mte90** [comment]
Thanks for the fix.
About the first issue, as I can see the sqlite file is created but is just empty with no table, so when you open xhgui you get an error with the stacktrace (that mention to check mongo also if not used).
So maybe a more welcome message like "do some scans with xhgui so this page will be filled" (my english is horrible) is better.

**Comment by glensc** [comment]
this isn't solved yet. the issue was closed automatically due to the merge and you reporting two problems in one issue. so only 50% is fixed.

**Comment by glensc** [comment]
perhaps opening SQLite db creates the file. I'm thinking of lazy init the table if an error of unknown table occurs.

**Comment by Mte90** [comment]
Seems a good idea so it is less heavy for performance.

**Comment by glensc** [comment]
also, you did not reply to my question:
> does your problem go away if you record one profiling?

**Comment by Mte90** [comment]
Sorry I am testing everything now and I get this error inside XHGUI:
```
<b>Fatal error</b>:  Uncaught TypeError: Argument 2 passed to XHGui\Db\PdoRepository::findByUrl() must be of the type string, null given, called in /srv/www/default/xhgui/src/Xhgui/Searcher/PdoSearcher.php on line 117 and defined in /srv/www/default/xhgui/src/Xhgui/Db/PdoRepository.php:96
Stack trace:
#0 /srv/www/default/xhgui/src/Xhgui/Searcher/PdoSearcher.php(117): XHGui\Db\PdoRepository-&gt;findByUrl('', NULL, 0, 25)
#1 /srv/www/default/xhgui/src/Xhgui/Controller/RunController.php(48): XHGui\Searcher\PdoSearcher-&gt;getAll(Array)
#2 /srv/www/default/xhgui/src/routes.php(45): XHGui\Controller\RunController-&gt;index(Object(Slim\Http\Request), Object(Slim\Http\Response))
#3 [internal function]: {closure}()
#4 /srv/www/default/xhgui/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#5 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route-&gt;dispatch()
#6 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim-&gt;call()
#7 /srv/www/default/xhgui/vendor/slim/slim/Slim/M in <b>/srv/www/default/xhgui/src/Xhgui/Db/PdoRepository.php</b> on line <b>96</b><br />
```
Also if I profile a page.

**Comment by glensc** [comment]
The submit some profiling message dialog is already there

```
Looks like you haven't done any profiling
To get started with XHGUI you'll need to collect some profiling data.

See Profiling a Web Request or CLI script section of the readme file
```

**Comment by glensc** [comment]
Initialize schema on PdoRepository construction:
- https://github.com/perftools/xhgui/pull/355

if someone wishes to make it on demand, I would not say no to a PR that does it portaby :)

**Comment by Mte90** [comment]
Seems everything fixed now :-)
